SERVICE_IP = "localhost"
SERVICE_PORT = "8080"
DATABASE = "postgres"
DB_SERVER = "localhost"
DB_PORT = "5432"
DB_USER = "postgres"
DB_PASSWORD = "password"
DB_DATABASE = "ai_resume_dean"
API_SECRET = "A440A46BE60093952E8BC87BB1C7627E70B991246167676FED65E0E6851B010A"